server:
  port: 8888
spring:
  jackson:
    serialization:
      WRITE_DATES_AS_TIMESTAMPS: false
  #MVC
  mvc:
    view:
      prefix: /
      suffix: .html
  resources:
    static-locations: classpath:/META-INF/resources/,classpath:/resources/,classpath:/static/,classpath:/public/