INSERT INTO USERS (ID, USERNAME, PASSWORD, ENABLED) VALUES (1,'zhangsan','11111',TRUE);
INSERT INTO USERS (ID, USERNAME, PASSWORD, ENABLED) VALUES (2,'lisi','11111',TRUE);
INSERT INTO USERS (ID, USERNAME, PASSWORD, ENABLED) VALUES (3,'wangwu','11111',TRUE);
INSERT INTO ROLES (ID, NAME) VALUES (1,'ADMIN');
INSERT INTO ROLES (ID, NAME) VALUES (2,'MANAGER');
INSERT INTO ROLES (ID, NAME) VALUES (3,'USER');
INSERT INTO RESOURCES (ID, URL, METHOD) VALUES (1,'/users',NULL);
INSERT INTO RESOURCES (ID, URL, METHOD) VALUES (2,'/users/**','GET');
INSERT INTO RESOURCES (ID, URL, METHOD) VALUES (3,'/users/*roles','POST');
INSERT INTO RESOURCES (ID, URL, METHOD) VALUES (4,'/users/roles*','PUT');
INSERT INTO RESOURCES (ID, URL, METHOD) VALUES (5,'/users/roles*/*','PATCH');
INSERT INTO RESOURCES (ID, URL, METHOD) VALUES (6,'/users/roles*/**','DELETE');

INSERT INTO USERS_ROLES (USER_ID, ROLE_ID) VALUES (1,1);
INSERT INTO USERS_ROLES (USER_ID, ROLE_ID) VALUES (1,2);
INSERT INTO USERS_ROLES (USER_ID, ROLE_ID) VALUES (1,3);
INSERT INTO USERS_ROLES (USER_ID, ROLE_ID) VALUES (2,2);
INSERT INTO USERS_ROLES (USER_ID, ROLE_ID) VALUES (3,3);

INSERT INTO ROLES_RESOURCES (ROLE_ID, RESOURCE_ID) VALUES (1,1);
INSERT INTO ROLES_RESOURCES (ROLE_ID, RESOURCE_ID) VALUES (1,2);
INSERT INTO ROLES_RESOURCES (ROLE_ID, RESOURCE_ID) VALUES (1,3);
INSERT INTO ROLES_RESOURCES (ROLE_ID, RESOURCE_ID) VALUES (1,4);
INSERT INTO ROLES_RESOURCES (ROLE_ID, RESOURCE_ID) VALUES (1,5);
INSERT INTO ROLES_RESOURCES (ROLE_ID, RESOURCE_ID) VALUES (1,6);
INSERT INTO ROLES_RESOURCES (ROLE_ID, RESOURCE_ID) VALUES (2,2);
INSERT INTO ROLES_RESOURCES (ROLE_ID, RESOURCE_ID) VALUES (2,3);
INSERT INTO ROLES_RESOURCES (ROLE_ID, RESOURCE_ID) VALUES (2,4);
INSERT INTO ROLES_RESOURCES (ROLE_ID, RESOURCE_ID) VALUES (2,5);
INSERT INTO ROLES_RESOURCES (ROLE_ID, RESOURCE_ID) VALUES (3,2);

INSERT INTO USERS_ACCESSTOKEN (USER_ID, ACCESS_TOKEN, PERSISTENT) VALUES (1,'1234567890',TRUE);

INSERT INTO LIST_SAMPLE (index,title,author,status,pageviews,display_time) VALUES (0,'test_title','Acer','published',222,'2018-01-01');
INSERT INTO LIST_SAMPLE (index,title,author,status,pageviews,display_time) VALUES (0,'test_title2','Mark','draft',222,'2018-02-11');
INSERT INTO LIST_SAMPLE (index,title,author,status,pageviews,display_time) VALUES (0,'sdf','Leo','deleted',222,'2018-01-01');